name: messenger

services:
  redis:
    image: redis:latest
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=messageapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iSrhowP8v2VAVZAJbvNC
    ports:
      - "8010:5432"
  web:
    build:
      context: ./messenger
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./messenger/:/usr/src/message_app/
    ports:
      - "8000:8000"
    env_file: .env.dev
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
