services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - media_volume:/home/message_app/web/media
  redis:
    image: redis:latest
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./.env.prod.db
    ports:
      - "8001:5432"
  web:
    build:
      context: ./messenger
      dockerfile: Dockerfile.prod
    command: daphne -b 0.0.0.0 -p 8000 messenger.asgi:application
    expose:
      - 8000
    env_file: .env.dev.prod
    volumes:
      - media_volume:/home/message_app/web/media
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  media_volume:
