# Generated by Django 4.2.6 on 2023-10-17 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chating_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
