# Generated by Django 4.2.6 on 2023-11-07 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message_app_chating', '0004_message_file_alter_message_chat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('first_user', 'second_user')},
        ),
    ]
