# Generated by Django 4.2.6 on 2023-12-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app_chating', '0006_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
