# Generated by Django 4.2.6 on 2024-01-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app_chating', '0009_groupchat_membership_alter_chat_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='name',
            field=models.CharField(default='Hey', max_length=30),
            preserve_default=False,
        ),
    ]
