# Generated by Django 4.2.6 on 2024-01-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app_chating', '0009_groupchat_membership_alter_chat_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
