# Generated by Django 4.2.5 on 2023-09-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_counter',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
