# Generated by Django 4.2.5 on 2023-09-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chating_user', '0002_remove_user_otp_counter_user_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hmac_key',
        ),
    ]
