# Generated by Django 4.2.6 on 2024-01-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating_user', '0002_alter_chatprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatprofile',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
